### ISSUE TITLE
Application crash after turning on vpn button.

### ISSUE THREAD

**Issue by skyuse** [vikulin/crispa-android#11]
I tried different peers, but the application crashes with absolutely any peers.

java.lang.RuntimeException: Unable to start service. listen udp6 [::]:9001: protocol not available

**Comment by skyuse** [comment]
<<< log_count = 120 >>>
[07-23 22:22:53.080 5131:5131 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: io.github.chronosx88.yggdrasil, PID: 5131
java.lang.RuntimeException: Unable to start service org.yggdrasil.app.crispa.YggdrasilTunService@2a7cae with Intent { cmp=io.github.chronosx88.yggdrasil/org.yggdrasil.app.crispa.YggdrasilTunService (has extras) }: go.Universe$proxyerror: listen udp6 [::]:9001: protocol not available
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4339)
	at android.app.ActivityThread.access$1800(ActivityThread.java:238)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1952)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:200)
	at android.os.Looper.loop(Looper.java:286)
	at android.app.ActivityThread.main(ActivityThread.java:7666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: go.Universe$proxyerror: listen udp6 [::]:9001: protocol not available
	at mobile.Yggdrasil.startJSON(Native Method)
	at org.yggdrasil.app.crispa.YggdrasilTunService.setupTunInterface(YggdrasilTunService.kt:122)
	at org.yggdrasil.app.crispa.YggdrasilTunService.onStartCommand(YggdrasilTunService.kt:62)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4321)
	... 9 more

[07-23 22:22:54.869 5305:5305 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: io.github.chronosx88.yggdrasil, PID: 5305
java.lang.RuntimeException: Unable to start service org.yggdrasil.app.crispa.YggdrasilTunService@c592701 with Intent { cmp=io.github.chronosx88.yggdrasil/org.yggdrasil.app.crispa.YggdrasilTunService (has extras) }: go.Universe$proxyerror: listen udp6 [::]:9001: protocol not available
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4339)
	at android.app.ActivityThread.access$1800(ActivityThread.java:238)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1952)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:200)
	at android.os.Looper.loop(Looper.java:286)
	at android.app.ActivityThread.main(ActivityThread.java:7666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: go.Universe$proxyerror: listen udp6 [::]:9001: protocol not available
	at mobile.Yggdrasil.startJSON(Native Method)
	at org.yggdrasil.app.crispa.YggdrasilTunService.setupTunInterface(YggdrasilTunService.kt:122)
	at org.yggdrasil.app.crispa.YggdrasilTunService.onStartCommand(YggdrasilTunService.kt:62)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4321)
	... 9 more
